improve scripts

diff --git a/scripts/pull-updates b/scripts/pull-updates
--- a/scripts/pull-updates
+++ b/scripts/pull-updates
@@ -1,3 +1,14 @@
-git stash
+HC=$(git rev-parse HEAD)
+git stash -u
 git pull
-git stash pop
+if ! git stash pop
+then
+  git reset --hard $HC
+  git stash pop
+  echo "We cannot get the latest changes to the class materials, because you have local changes that conflict with them."
+  echo "To erase your local changes, run the command `reset-all`."
+  echo "(Warning: this cannot be undone.)"
+  echo "Remember that you should only be modifying files in your personal working directories."
+else 
+  lake exe cache get
+fi
